apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/anildiwan/argocd-app-config-main.git
    targetRevision: HEAD
    path: dev/mongo-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: mongodb

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: false
      prune: true