apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/anildiwan/argocd-app-config-main.git
    targetRevision: HEAD
    path: dev/mongo-app
    
  destination: 
    server: https://kubernetes.default.svc
    namespace: mongodb

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: false
      prune: true
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mongoexpress-virtualservice
  namespace: myapp
spec:
  hosts:
  - "*"
  gateways:
  - myapp-gateway
  http:
  - match:
    - uri:
        prefix: /mongo-express
    route:
    - destination:
        host: mongoexpress-service
        port:
          number: 8081
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mongoexpress-destinationrule
  namespace: myapp
spec:
  host: mongoexpress-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
      